# -*- coding: utf-8 -*-
"""1210_VAR_시범.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AGKPbt95m1WEkhfoh9UtWQj1ApW2Lhbj

**df_var_1209.csv를 불러와서 VAR를 실시하고자 함**
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

path = "/content/drive/MyDrive/Aiffelthon/df_var_1209.csv"
df_var = pd.read_csv(path)

df_var.head()

df_var.info()

df_var.isna().sum()

#time 칼럼을 datetime으로 변환
df_var['time'] = pd.to_datetime(df_var['time'])
df_var = df_var.set_index('time')

# VAR에 들어갈 변수 subset 만들기

var_cols = [
    'ret_log_1d',
    'oi_close_diff',
    'funding_close',
    'liq_total_usd_diff',
    'taker_buy_ratio',
    'sth_sopr',
    'lth_sopr',
    'sth_realized_price_usd_diff',
    'lth_realized_price_usd_diff',
    'rhodl_ratio',
    'global_m2_yoy_diff',
    'sp500_ret',
    'nasdaq_ret',
    'etf_aum_diff'
]

df_var_sub = df_var[var_cols]

from statsmodels.tsa.stattools import adfuller

for col in df_var_sub.columns:
    p = adfuller(df_var_sub[col])[1]
    print(f'{col} → p-value = {p:.4f}')

var_cols_final = [
    'ret_log_1d',
    'oi_close_diff',
    'funding_close',
    'liq_total_usd_diff',
    'taker_buy_ratio',
    'sth_sopr',
    'lth_sopr',
    'sth_realized_price_usd_diff',
    'lth_realized_price_usd_diff',
    'global_m2_yoy_diff',
    'sp500_ret',
    'nasdaq_ret',
    'etf_aum_diff'
]

from statsmodels.tsa.api import VAR

model = VAR(df_var[var_cols_final])
lag_selection = model.select_order(maxlags=10)
print(lag_selection.summary())

# 1. 인덱스가 time이고, 일단위 시계열임을 명시 (선택이지만 추천)
df_var = df_var.asfreq('D')

# 2. VAR에 쓸 최종 컬럼만 선택
var_cols_final = [
    'ret_log_1d',
    'oi_close_diff',
    'funding_close',
    'liq_total_usd_diff',
    'taker_buy_ratio',
    'sth_sopr',
    'lth_sopr',
    'sth_realized_price_usd_diff',
    'lth_realized_price_usd_diff',
    'global_m2_yoy_diff',
    'sp500_ret',
    'nasdaq_ret',
    'etf_aum_diff'
]

df_var_final = df_var[var_cols_final]

from statsmodels.tsa.api import VAR

model = VAR(df_var_final)
var_result = model.fit(1)  # lag = 1
print(var_result.summary())

from statsmodels.tsa.stattools import grangercausalitytests

target = 'ret_log_1d'
variables = ['oi_close_diff', 'liq_total_usd_diff', 'taker_buy_ratio', 'etf_aum_diff']

for var in variables:
    print(f"\n### Testing whether {var} Granger-causes {target}")
    grangercausalitytests(df_var_final[[target, var]], maxlag=1, verbose=True)

import matplotlib.pyplot as plt

# 1. IRF 객체 생성 (예: 10일 반응)
irf = var_result.irf(10)  # horizon=10일

# 2. 전체 변수 간 IRF 플롯
irf.plot(orth=False)
plt.show()

import matplotlib.pyplot as plt

irf = var_result.irf(10)  # 10일 기준

fig = irf.plot(impulse='oi_close_diff', response='ret_log_1d', orth=False)
plt.title('IRF: oi_close_diff shock → ret_log_1d')
plt.show()

fig = irf.plot(impulse='liq_total_usd_diff', response='ret_log_1d', orth=False)
plt.title('IRF: liq_total_usd_diff shock → ret_log_1d')
plt.show()

fig = irf.plot(impulse='taker_buy_ratio', response='ret_log_1d', orth=False)
plt.title('IRF: taker_buy_ratio shock → ret_log_1d')
plt.show()

fig = irf.plot(impulse='etf_aum_diff', response='ret_log_1d', orth=False)
plt.title('IRF: etf_aum_diff shock → ret_log_1d')
plt.show()

irf_values = irf.irfs  # shape: (horizon+1, n_vars, n_vars)
irf_values.shape

var_names = var_result.names
print(var_names)

# impulse='liq_total_usd_diff', response='ret_log_1d' 인덱스 찾기
i_response = var_names.index('ret_log_1d')
i_impulse = var_names.index('liq_total_usd_diff')

# 0~10일 반응 수치
irf_liq_to_ret = irf_values[:, i_response, i_impulse]
print(irf_liq_to_ret)

import numpy as np
import pandas as pd

# 10일 horizon으로 IRF 계산
irf = var_result.irf(10)
irf_values = irf.irfs          # shape: (horizon+1, n_eq, n_shock)
var_names = var_result.names   # VAR에 들어간 변수 이름 리스트
print(var_names)

# 현실적인 shock 크기들
liq_shocks = [1e8, 5e8, 1e9]          # 1억, 5억, 10억 달러
taker_shocks = [0.01, 0.05, 0.10]     # +1%, +5%, +10% 포인트
etf_shocks = [1e8, 5e8, 1e9]          # 1억, 5억, 10억 달러

# 보고 싶은 horizon (일)
horizons = [1, 3, 5, 10]              # 1일, 3일, 5일, 10일

def scaled_irf_table(
    irf_values,
    var_names,
    response_name,
    impulse_name,
    shock_list,
    horizons,
    label_prefix
):
    """
    response_name: 'ret_log_1d'
    impulse_name : 'liq_total_usd_diff' 등
    shock_list   : 현실 shock 크기 리스트
    horizons     : [1,3,5,10] 같이 보고 싶은 일수
    label_prefix : 'liq', 'taker', 'etf' 등
    """
    i_resp = var_names.index(response_name)
    i_imp  = var_names.index(impulse_name)

    rows = []
    for s in shock_list:
        row = {}
        for h in horizons:
            # statsmodels: index 0 = 1-step ahead
            irf_h = irf_values[h-1, i_resp, i_imp]   # 1단위 shock 기준 log return 변화
            # 현실 shock scale 적용 후, % 단위 수익률로 변환
            delta_pct = irf_h * s * 100.0
            row[f'h={h}d'] = delta_pct
        rows.append(pd.Series(row, name=f'{label_prefix}_shock={s: .2e}'))

    return pd.DataFrame(rows)

# 1) 청산 shock → ret_log_1d
fe_irf_liq = scaled_irf_table(
    irf_values,
    var_names,
    response_name='ret_log_1d',
    impulse_name='liq_total_usd_diff',
    shock_list=liq_shocks,
    horizons=horizons,
    label_prefix='liq'
)

# 2) Taker Buy Ratio shock → ret_log_1d
fe_irf_taker = scaled_irf_table(
    irf_values,
    var_names,
    response_name='ret_log_1d',
    impulse_name='taker_buy_ratio',
    shock_list=taker_shocks,
    horizons=horizons,
    label_prefix='taker'
)

# 3) ETF AUM shock → ret_log_1d
fe_irf_etf = scaled_irf_table(
    irf_values,
    var_names,
    response_name='ret_log_1d',
    impulse_name='etf_aum_diff',
    shock_list=etf_shocks,
    horizons=horizons,
    label_prefix='etf'
)

fe_irf_liq, fe_irf_taker, fe_irf_etf

# 세 테이블을 하나로 붙이고 보기 좋게 반올림
fe_irf_all = (
    pd.concat([fe_irf_liq, fe_irf_taker, fe_irf_etf])
      .round(4)   # %단위 소수 4자리
)

fe_irf_all

# h=1d 기준으로 영향력 크기 순 정렬
fe_irf_all.sort_values(by='h=1d', ascending=True)  # 하락 충격 크기 기준

horizons = list(range(1, 11))   # 1~10일 전체

# 청산 shock → ret_log_1d
fe_irf_liq = scaled_irf_table(
    irf_values,
    var_names,
    response_name='ret_log_1d',
    impulse_name='liq_total_usd_diff',
    shock_list=liq_shocks,
    horizons=horizons,
    label_prefix='liq'
)

# Taker Buy Ratio shock → ret_log_1d
fe_irf_taker = scaled_irf_table(
    irf_values,
    var_names,
    response_name='ret_log_1d',
    impulse_name='taker_buy_ratio',
    shock_list=taker_shocks,
    horizons=horizons,
    label_prefix='taker'
)

# ETF AUM shock → ret_log_1d
fe_irf_etf = scaled_irf_table(
    irf_values,
    var_names,
    response_name='ret_log_1d',
    impulse_name='etf_aum_diff',
    shock_list=etf_shocks,
    horizons=horizons,
    label_prefix='etf'
)

# 세 개 모두 결합
fe_irf_all = (
    pd.concat([fe_irf_liq, fe_irf_taker, fe_irf_etf])
    .round(6)
)

fe_irf_all

import matplotlib.pyplot as plt

# horizon 값 자동 생성 (1~10일)
horizons = list(range(1, 11))

# fe_irf_all의 row 이름을 순회하면서 그래프 그리기
plt.figure(figsize=(12, 8))

for idx, row in fe_irf_all.iterrows():
    plt.plot(horizons, row.values, marker='o', label=idx)

plt.axhline(0, color='black', linewidth=1)
plt.title('IRF (shock scale)', fontsize=16)
plt.xlabel('Days after Shock', fontsize=13)
plt.ylabel('Price Impact (%)', fontsize=13)
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.show()

print(fe_irf_all.index.tolist())

import matplotlib.pyplot as plt

# 1~10일 horizon
horizons = list(range(1, 11))

# 🔧 index에서 'liq_shock'가 들어간 행만 선택 (axis=0이 중요!)
liq_rows = fe_irf_all.filter(like='liq_shock', axis=0)

plt.figure(figsize=(10,6))

for idx, row in liq_rows.iterrows():
    plt.plot(horizons, row.values, marker='o', label=idx)

plt.axhline(0, color='black', linewidth=1)
plt.title('Shock → Price Impact (%)', fontsize=15)
plt.xlabel('Days', fontsize=12)
plt.ylabel('Impact (%)', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

taker_rows = fe_irf_all.filter(like='taker_shock', axis=0)

plt.figure(figsize=(10,6))
for idx, row in taker_rows.iterrows():
    plt.plot(horizons, row.values, marker='o', label=idx)

plt.axhline(0, color='black', linewidth=1)
plt.title('Taker Buy Ratio Shock → Price Impact (%)', fontsize=15)
plt.xlabel('Days', fontsize=12)
plt.ylabel('Impact (%)', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

etf_rows = fe_irf_all.filter(like='etf_shock', axis=0)

plt.figure(figsize=(10,6))
for idx, row in etf_rows.iterrows():
    plt.plot(horizons, row.values, marker='o', label=idx)

plt.axhline(0, color='black', linewidth=1)
plt.title('ETF AUM Shock → Price Impact (%)', fontsize=15)
plt.xlabel('Days', fontsize=12)
plt.ylabel('Impact (%)', fontsize=12)
plt.legend()
plt.grid(True)
plt.show()

fevd = var_result.fevd(10)
fevd.summary()

fevd = var_result.fevd(10)
print(fevd.summary())

fevd = var_result.fevd(10)

var_names = var_result.names
i_ret = var_names.index("ret_log_1d")

rows = []
for h in range(1, 11):
    contrib = fevd.decomp[h-1, i_ret, :] * 100
    rows.append(contrib)

fevd_ret = pd.DataFrame(rows,
                        index=range(1, 11),
                        columns=var_names).round(3)
fevd_ret.index.name = "horizon"
fevd_ret

import matplotlib.pyplot as plt
import seaborn as sns

# fevd_ret: 이미 존재하는 FEVD 결과 DataFrame (horizon × shocks)

plt.figure(figsize=(14, 8))

sns.heatmap(
    fevd_ret,
    annot=True,
    fmt=".1f",
    cmap="YlGnBu",
    cbar=True
)

plt.title("FEVD Heatmap for ret_log_1d (Horizon 1~10 Days)", fontsize=16)
plt.xlabel("Shock Variables", fontsize=12)
plt.ylabel("Horizon (Days)", fontsize=12)

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np

# 1️⃣ time이 컬럼인지 / 인덱스인지에 따라 기준 날짜 처리
if 'time' in df_var.columns:
    df_var['time'] = pd.to_datetime(df_var['time'])
    df_var = df_var.sort_values('time')
    latest = df_var.iloc[-1]
    ref_date = latest['time'].date()
else:
    # time이 인덱스로 존재하는 경우
    if not isinstance(df_var.index, pd.DatetimeIndex):
        df_var.index = pd.to_datetime(df_var.index)
    df_var = df_var.sort_index()
    latest = df_var.iloc[-1]
    ref_date = df_var.index[-1].date()

# 2️⃣ 신호등 함수들 그대로 사용
def signal_oi(oi_diff):
    if oi_diff > 1_000_000_000:   # +10억 이상 증가
        return "🔴 HIGH (레버리지 과열)"
    elif oi_diff > 300_000_000:   # +3억 ~ 10억
        return "🟡 CAUTION (레버리지 증가)"
    else:
        return "🟢 NORMAL"

def signal_funding(funding):
    if abs(funding) > 0.0003:   # ±0.03% 이상
        return "🔴 HIGH (극단적 펀딩)"
    elif abs(funding) > 0.0001: # ±0.01% ~ 0.03%
        return "🟡 CAUTION"
    else:
        return "🟢 NORMAL"

def signal_liq(liq_usd):
    liq_abs = abs(liq_usd)
    if liq_abs > 200_000_000:      # 2억 이상
        return "🔴 HIGH (대규모 청산)"
    elif liq_abs > 50_000_000:     # 5천만 ~ 2억
        return "🟡 CAUTION (청산 확대)"
    else:
        return "🟢 NORMAL"

def signal_taker(taker_ratio):
    if taker_ratio > 0.60 or taker_ratio < 0.40:
        return "🔴 HIGH (매수/매도 한쪽 쏠림)"
    elif taker_ratio > 0.55 or taker_ratio < 0.45:
        return "🟡 CAUTION (편향 존재)"
    else:
        return "🟢 NORMAL"

def signal_m2(m2_diff):
    if m2_diff < 0:
        return "🔴 TIGHT (유동성 축소)"
    elif m2_diff < 0.01:
        return "🟡 NEUTRAL"
    else:
        return "🟢 LOOSE (유동성 확대)"

# 3️⃣ 각 신호 계산
sig_oi   = signal_oi(latest['oi_close_diff'])
sig_fund = signal_funding(latest['funding_close'])
sig_liq  = signal_liq(latest['liq_total_usd_diff'])
sig_taker= signal_taker(latest['taker_buy_ratio'])
sig_m2   = signal_m2(latest['global_m2_yoy_diff'])

def score_from_signal(s):
    if s.startswith("🔴"):
        return 2
    elif s.startswith("🟡"):
        return 1
    else:
        return 0

total_score = sum([
    score_from_signal(sig_oi),
    score_from_signal(sig_fund),
    score_from_signal(sig_liq),
    score_from_signal(sig_taker),
    score_from_signal(sig_m2)
])

if total_score >= 6:
    overall = "🔴 HIGH RISK (단기 변동성·청산 리스크 매우 큼)"
elif total_score >= 3:
    overall = "🟡 CAUTION (포지션 관리 필요)"
else:
    overall = "🟢 NORMAL (구조적 과열 신호 약함)"

# 4️⃣ 최종 출력
print("━━━━━━━━━━━━━━━━━━━━━━")
print(f"  Bitcoin Risk Dashboard (기준일: {ref_date})")
print("━━━━━━━━━━━━━━━━━━━━━━\n")

print("[ 레버리지 구조 ]")
print(f"OI 변화량 (oi_close_diff):      {sig_oi}   (값: {latest['oi_close_diff']:,.0f})")
print(f"Funding Rate (funding_close):   {sig_fund} (값: {latest['funding_close']:.5f})")
print(f"Liquidation USD (liq_total):    {sig_liq}  (값: {latest['liq_total_usd_diff']:,.0f})\n")

print("[ 시장 흐름 (Flow) ]")
print(f"Taker Buy Ratio:                {sig_taker} (값: {latest['taker_buy_ratio']:.3f})\n")

print("[ 거시 유동성 ]")
print(f"Global M2 YoY Diff:             {sig_m2} (값: {latest['global_m2_yoy_diff']:.3f})\n")

print("━━━━━━━━━━━━━━━━━━━━━━")
print(f"  종합 위험도: {overall}")
print("━━━━━━━━━━━━━━━━━━━━━━")

# 🔹 방금 계산한 latest, sig_oi, sig_fund, sig_liq, sig_taker, sig_m2, overall 그대로 사용

def explain_oi(sig, val):
    if sig.startswith("🔴"):
        return (
            f"- 레버리지 포지션: {sig} / 최근 OI가 {val:,.0f} USD 증가해 "
            "과거 평균 대비 레버리지가 크게 쌓인 구간입니다. "
            "작은 가격 충격에도 강한 청산이 연쇄적으로 나올 수 있는 상태입니다."
        )
    elif sig.startswith("🟡"):
        return (
            f"- 레버리지 포지션: {sig} / OI가 {val:,.0f} USD 증가한 수준으로, "
            "레버리지가 완만히 늘어나며 단기 변동성이 커진 상황입니다. "
            "다만 아직 ‘극단적 과열’ 수준까지는 아니었습니다."
        )
    else:
        return (
            f"- 레버리지 포지션: {sig} / OI 변화가 {val:,.0f} USD 수준으로, "
            "레버리지가 과거 평균 또는 그 이하로 안정된 상태입니다. "
            "레버리지 청산발 급락 위험은 제한적인 편입니다."
        )

def explain_funding(sig, val):
    if sig.startswith("🔴"):
        return (
            f"- 펀딩 비율: {sig} / Funding Rate ≈ {val:.3%} 로, "
            "롱 혹은 숏 한쪽으로 포지션이 과도하게 쏠린 상태입니다. "
            "과거 VAR/IRF 분석 기준, 이런 구간에서는 단기적으로 되돌림 변동성이 커지는 패턴이 자주 관찰되었습니다."
        )
    elif sig.startswith("🟡"):
        return (
            f"- 펀딩 비율: {sig} / Funding Rate ≈ {val:.3%} 수준으로, "
            "한쪽 포지션이 우세하긴 하지만 아직 극단적은 아닙니다. "
            "현재 가격 움직임은 ‘포지션 조정 구간’에 가깝다고 볼 수 있습니다."
        )
    else:
        return (
            f"- 펀딩 비율: {sig} / Funding Rate ≈ {val:.3%} 로, "
            "롱·숏 균형이 비교적 잘 맞는 상태입니다. "
            "가격 급등·급락이 나와도 레버리지 포지션이 추가로 부채질할 가능성은 크지 않습니다."
        )

def explain_liq(sig, val):
    if sig.startswith("🔴"):
        return (
            f"- 청산 규모: {sig} / 일간 청산 규모가 약 {abs(val):,.0f} USD 로, "
            "직접적인 강제 청산이 가격 변동을 주도한 날에 가깝습니다. "
            "이 경우 가격 급락은 펀더멘털보다는 레버리지 구조 해소 성격이 강합니다."
        )
    elif sig.startswith("🟡"):
        return (
            f"- 청산 규모: {sig} / 청산 규모가 약 {abs(val):,.0f} USD 로, "
            "강제 청산이 점진적으로 늘어나는 구간입니다. "
            "추가 변동성에 대비해 레버리지 비중을 줄이는 것이 유리할 수 있습니다."
        )
    else:
        return (
            f"- 청산 규모: {sig} / 청산 규모가 약 {abs(val):,.0f} USD 로, "
            "직접적인 레버리지 강제 청산이 시장을 흔드는 수준은 아닙니다. "
            "최근 움직임은 ‘포지션 강제 정리’보다는 심리·현물 수급에 더 가깝다고 해석할 수 있습니다."
        )

def explain_taker(sig, val):
    if sig.startswith("🔴"):
        return (
            f"- 매수·매도 쏠림: {sig} / Taker Buy Ratio ≈ {val:.3f} 로, "
            "단기적으로 매수 또는 매도 한쪽 방향으로 거래가 과도하게 쏠려 있습니다. "
            "이 구간에서는 반대 방향 스파이크(숏·롱 스퀴즈)가 자주 발생할 수 있습니다."
        )
    elif sig.startswith("🟡"):
        return (
            f"- 매수·매도 쏠림: {sig} / Taker Buy Ratio ≈ {val:.3f} 으로, "
            "한쪽 방향으로 우위가 있지만 아직 ‘극단적 공포/탐욕’ 단계는 아닙니다. "
            "단기 변동성이 커질 수 있어 레버리지 관리가 중요합니다."
        )
    else:
        return (
            f"- 매수·매도 쏠림: {sig} / Taker Buy Ratio ≈ {val:.3f} 으로, "
            "매수·매도 흐름이 비교적 균형 잡혀 있습니다. "
            "가격 움직임이 특정 방향으로 ‘몰려서’ 나오는 국면은 아닙니다."
        )

def explain_m2(sig, val):
    if sig.startswith("🔴"):
        return (
            f"- 글로벌 유동성(M2): {sig} / 최근 YoY Diff ≈ {val:.3%} 수준으로, "
            "거시 유동성이 축소되는 환경입니다. "
            "위험자산 전반에 ‘리레이팅 하락’이 동반될 가능성을 염두에 둘 필요가 있습니다."
        )
    elif sig.startswith("🟡"):
        return (
            f"- 글로벌 유동성(M2): {sig} / YoY Diff ≈ {val:.3%} 수준으로, "
            "유동성 측면에서 뚜렷한 팽창·축소 신호가 아닌 중립 구간입니다. "
            "현재 비트코인 변동은 거시보다는 ‘시장 내부 구조(레버리지, ETF, 온체인)’ 영향이 더 클 가능성이 높습니다."
        )
    else:
        return (
            f"- 글로벌 유동성(M2): {sig} / YoY Diff ≈ {val:.3%} 수준으로, "
            "완만한 유동성 확대 국면에 가깝습니다. "
            "단기 조정이 있어도 중장기 관점에서는 유동성 환경이 뒷받침되는 구조입니다."
        )

def summarize_overall(overall_signal):
    if overall_signal.startswith("🔴"):
        return (
            "▶ 종합 해석: 레버리지·펀딩·청산·유동성 신호가 동시에 악화된 **고위험 구간**입니다.\n"
            "  - 과거 VAR/IRF 분석 기준, 이런 시기에는 단기 급락/급등 스파이크가 반복되는 경향이 강했습니다.\n"
            "  - 이 구간에서의 ‘추격 매수/추격 매도’는 손실 확대로 이어질 가능성이 높습니다.\n"
            "  - 전략: 레버리지 축소, 손절 폭 축소, 현금 비중 확대 등 **리스크 관리 우선**이 합리적입니다."
        )
    elif overall_signal.startswith("🟡"):
        return (
            "▶ 종합 해석: 일부 레버리지·펀딩 지표가 과열 또는 일시적 쏠림을 보이는 **주의 구간**입니다.\n"
            "  - 현재 조정은 구조적 붕괴라기보다, 레버리지 포지션 조정과 단기 심리 요인이 섞인 국면일 가능성이 큽니다.\n"
            "  - 과거 유사 구간에서는 수 일~수 주 내에 되돌림이 자주 관찰되었고, ‘패닉셀’보다는 포지션 재조정이 유리했습니다.\n"
            "  - 전략: 방향성 도박보다는 레버리지 관리, 분할 접근, 손익비가 맞는 구간에서의 제한적 대응이 적합합니다."
        )
    else:
        return (
            "▶ 종합 해석: 레버리지·청산·유동성 모두에서 **과열 신호가 강하지 않은 정상 구간**입니다.\n"
            "  - 단기 조정이 있더라도 구조적 레버리지 청산이나 매크로 쇼크가 주된 원인일 가능성은 낮습니다.\n"
            "  - 장기 보유자 입장에서는 ‘구조적 리스크보다는 노이즈에 가까운 변동’으로 볼 여지가 큽니다.\n"
            "  - 전략: 패닉셀보다는, 본인의 투자 기간·리스크 허용도에 맞는 **계획된 리밸런싱**이 핵심입니다."
        )

# 🔻 실제 문장 생성
lines = []

lines.append(f"[1] 오늘 기준 요약 (기준일: {ref_date})")
lines.append(f"  → 종합 위험도: {overall}")
lines.append("")

lines.append("[2] 레버리지·선물 구조 해석")
lines.append("  " + explain_oi(sig_oi,   latest['oi_close_diff']))
lines.append("  " + explain_funding(sig_fund, latest['funding_close']))
lines.append("  " + explain_liq(sig_liq, latest['liq_total_usd_diff']))
lines.append("")

lines.append("[3] 현물·심리 및 유동성 환경")
lines.append("  " + explain_taker(sig_taker, latest['taker_buy_ratio']))
lines.append("  " + explain_m2(sig_m2, latest['global_m2_yoy_diff']))
lines.append("")

lines.append("[4] 투자 행동 관점 정리")
lines.append("  " + summarize_overall(overall))

dashboard_text = "\n".join(lines)
print(dashboard_text)

import numpy as np

# 1) horizon 정의 (1~10일)
horizons = list(range(1, fe_irf_all.shape[1] + 1))

def summarize_shock(row, horizons):
    """
    row: fe_irf_all의 한 행 (예: 'liq_shock= 1.00e+09')
    -> 최대 영향 시점, 회복 시점(80% 이상 감소), 10일 누적 영향 계산
    """
    impacts = row.values.astype(float)

    # 전부 0이면 None
    max_abs = np.max(np.abs(impacts))
    if max_abs == 0:
        return None

    # 피크(최대 절대값) 시점
    peak_idx = int(np.argmax(np.abs(impacts)))
    peak_day = horizons[peak_idx]
    peak_val = impacts[peak_idx]  # % 단위 (이미 fe_irf_all이 %라고 가정)

    # '충격의 80% 이상 흡수' 기준 (피크의 20% 이하가 되는 첫 날)
    threshold = 0.2 * max_abs
    recovery_day = None
    for h, imp in zip(horizons, impacts):
        if abs(imp) <= threshold:
            recovery_day = h
            break

    # 10일 누적 영향 (%포인트 합)
    cum_10d = impacts.sum()

    return {
        "peak_day": peak_day,
        "peak_impact": peak_val,
        "recovery_day": recovery_day,
        "cum_10d": cum_10d,
    }

# 2) 우리가 보고 싶은 대표 쇼크 3개 선택
row_liq   = fe_irf_all.loc['liq_shock= 1.00e+09']     # 10억 달러 청산
row_taker = fe_irf_all.loc['taker_shock= 1.00e-01']   # Taker Buy Ratio +0.10
row_etf   = fe_irf_all.loc['etf_shock= 1.00e+09']     # ETF AUM +10억 달러

summary_liq   = summarize_shock(row_liq, horizons)
summary_taker = summarize_shock(row_taker, horizons)
summary_etf   = summarize_shock(row_etf, horizons)

summary_liq, summary_taker, summary_etf

def line_for_liq(meta):
    if meta is None:
        return "- 청산 쇼크: 과거 데이터에서 유의미한 가격 반응이 관찰되지 않았습니다."
    return (
        f"- 대규모 청산 쇼크 (≈ 10억 달러 강제청산 가정): "
        f"{meta['peak_day']}일차에 최대 {meta['peak_impact']:.1f}% 변동이 나타났고, "
        f"대략 {meta['recovery_day']}일 이내에 충격의 대부분(약 80% 이상)이 흡수되는 패턴이었습니다. "
        f"(10일 누적 영향 ≈ {meta['cum_10d']:.1f}%p)"
    )

def line_for_taker(meta):
    if meta is None:
        return "- Taker 쏠림 쇼크: 과거 데이터에서 유의미한 가격 반응이 관찰되지 않았습니다."
    return (
        f"- Taker Buy Ratio 쇼크 (+0.10p 가정): "
        f"{meta['peak_day']}일차에 최대 {meta['peak_impact']:.2f}% 영향이 관찰되었고, "
        f"{meta['recovery_day']}일 내에 대부분이 해소되었습니다. "
        f"(10일 누적 영향 ≈ {meta['cum_10d']:.2f}%p, 방향성보다는 단기 노이즈에 가까운 규모)"
    )

def line_for_etf(meta):
    if meta is None:
        return "- ETF AUM 쇼크: 과거 데이터에서 유의미한 가격 반응이 관찰되지 않았습니다."
    return (
        f"- ETF AUM 쇼크 (자금 유입 +10억 달러 가정): "
        f"{meta['peak_day']}일차에 최대 {meta['peak_impact']:.2f}%의 완만한 양(+)의 반응이 나타났고, "
        f"대략 {meta['recovery_day']}일 이내에 추가 효과는 제한적인 수준으로 줄었습니다. "
        f"(10일 누적 영향 ≈ {meta['cum_10d']:.2f}%p)"
    )

liq_line   = line_for_liq(summary_liq)
taker_line = line_for_taker(summary_taker)
etf_line   = line_for_etf(summary_etf)

print(liq_line)
print(taker_line)
print(etf_line)

lines = dashboard_text.split("\n")  # 기존 텍스트를 줄 단위로 쪼개고

lines.append("")
lines.append("━━━━━━━━━━━━━━━━━━━━━━")
lines.append("  과거 충격 흡수 속도 (IRF 기반 요약)")
lines.append("━━━━━━━━━━━━━━━━━━━━━━")
lines.append(liq_line)
lines.append(taker_line)
lines.append(etf_line)

dashboard_text_extended = "\n".join(lines)
print(dashboard_text_extended)

